name: GH-Pages
on:
  push:
    branches:
      - master
  pull_request:
permissions: 
  contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: npm install
      - run: npx nx build table-game --buildLibsFromSource --prod --baseHref=/My-app/
      - run: npx gh-pages -d dist/apps/table-game
